- Tella/Components.swift
- Tella/FileManager.swift
- Tella/Importers.swift
- Tella/Info.plist
- Tella/PreviewView.swift
- Tella/SettingsView.swift
Also fixed an issue with a missing close paren.
> added file export functionality

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation_change_template.md
- .github/ISSUE_TEMPLATE/new_feature_template.md
- .github/pull_request_template.md
> Issues and PR template

- Tella.xcodeproj/project.pbxproj
- Tella/AppViewState.swift
- Tella/CameraView.swift
- Tella/ChangeView.swift
- Tella/CollectView.swift
- Tella/Components.swift
- Tella/ContentView.swift
- Tella/GalleryView.swift
- Tella/MainView.swift
- Tella/PasswordView.swift
- Tella/PreviewView.swift
- Tella/RecordView.swift
- Tella/SceneDelegate.swift
- Tella/SettingsView.swift
- Tella/Util.swift
- Share view stack among views
- UI code updates
> Fix page redirection bug #19

- Tella.xcodeproj/project.pbxproj
- Tella/BundleInfo.swift
- Tella/SettingsView.swift
> Add app/build version to the Settings screen

- .vscode/settings.json
- Tella.xcodeproj/project.pbxproj
- Tella.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- Tella/Components/ConfirmationBottomSheet.swift
- Tella/Components/ImagePickerView.swift
- Tella/Data/MainAppModel.swift
- Tella/Scenes/HomeView/Views/FileListView/Add files/AddFileView.swift
- Tella/Scenes/HomeView/Views/FileListView/Add files/PhotoVideoPickerView.swift
- Tella/Scenes/HomeView/Views/FileListView/Add files/PhotoVideoViewModel.swift
- Tella/Scenes/HomeView/Views/Home/HomeView.swift
- Tella/Supporting Files/Info.plist
- Tella/Supporting Files/en.lproj/Localizable.strings
- Tella/Supporting Files/es.lproj/Localizable.strings
- Tella/Supporting Files/fr.lproj/Localizable.strings
- Tella/Utils/Localizable/LocalizableVault.swift
When user goes to folder > + > Import from device, Tella opens a second bottom sheet that says:
* Add new bottom sheet when user is importing a file from the device
* Add logic to remove photos and documents from the device
* Add new permissions so the app can access to the photo library
https://www.loom.com/share/54af4d5c1c5d4772af316ca345aefbab
> WIP Feature/add import and delete

- Tella/Components/ImagePickerSheet.swift
- Tella/Scenes/HomeView/Views/FileListView/Add files/PhotoVideoViewModel.swift
Fix deletion of videos after importing
> fix deletion of videos when importing

- Tella/Data/Database/TellaData.swift
- Tella/Data/Database/TellaDataBase.swift
- Tella/Scenes/Settings/ViewModel/ServersViewModel.swift
- Tella/Scenes/Settings/ViewModel/UwaziServerViewModel.swift
- Tella/Scenes/Uwazi/ViewModel/UwaziViewModel.swift
Changes suggested in the PR review
> Code improvements

- Tella/Supporting Files/ar.lproj/Localizable.strings
- Tella/Supporting Files/be.lproj/Localizable.strings
- Tella/Supporting Files/en.lproj/Localizable.strings
- Tella/Supporting Files/es-419.lproj/Localizable.strings
- Tella/Supporting Files/es.lproj/Localizable.strings
- Tella/Supporting Files/fa-IR.lproj/Localizable.strings
- Tella/Supporting Files/fr.lproj/Localizable.strings
- Tella/Supporting Files/ku.lproj/Localizable.strings
- Tella/Supporting Files/my.lproj/Localizable.strings
- Tella/Supporting Files/ta.lproj/Localizable.strings
- Tella/Utils/Localizable/LocalizableSettings.swift
Added the key Settings_SettSec_PreserveMetadata and Settings_SettSec_PreserveMetadata_Expl to other localization file 
> Preserve metadata localization issue fixed

- Tella/Components/ImagePickerSheet.swift
The photo or video picker is not returning the photo or video selected
*
*
*
> Issue with video and photo picker not working fixed

- Tella/Scenes/HomeView/ViewModel/HomeViewModel.swift
- Tella/Scenes/HomeView/Views/Home/HomeView.swift
> Caching issue connections

- Tella/Scenes/Reports/View Model/DraftReportVM.swift
> Solve the issue with uwazi server showing in new report of tella web

- Tella/Domain/Entity/Uwazi/Language/UwaziLanguageRow.swift
- Tella/Scenes/Settings/Views/Servers/Uwazi/Step5/UwaziLanguageSelectionView.swift
> Fix Uwazi languages crash

- Tella/Scenes/Settings/ViewModel/UwaziServerViewModel.swift
- Tella/Scenes/Settings/Views/Servers/Uwazi/Step1/UwaziAddServerURLView.swift
- Tella/Scenes/Settings/Views/Servers/Uwazi/Step3/UwaziLoginView.swift
> Uwazi edit flow login button issue

- Tella.xcodeproj/project.pbxproj
- Tella/Data/Networking/Repositories/UwaziServerRepositories.swift
- Tella/Scenes/Reports/Draft/EmptyReportView.swift
- Tella/Scenes/Uwazi/ViewModel/AddTemplateVM.swift
- Tella/Scenes/Uwazi/Views/Template/AddTemplatesView.swift
> Uwazi template download no internet connection

- Tella/Scenes/Settings/Views/Servers/EditSettingsServerView.swift
This PR adds a ScrollView in the editSettingsServerView because it was getting cutoff in small screens.
> add scroll view in EditSettingsServerView

- Tella.xcodeproj/project.pbxproj
- Tella/Data/FileWalker.swift
- Tella/Data/VaultManager/VaultFilesManager.swift
- Tella/Scenes/HomeView/Models/DeleteConfirmation.swift
- Tella/Scenes/HomeView/ViewModel/FileListViewModel.swift
- Tella/Scenes/HomeView/Views/FileListView/File list/MoreFileActionButton.swift
- Tella/Supporting Files/ar.lproj/Localizable.strings
- Tella/Supporting Files/be.lproj/Localizable.strings
- Tella/Supporting Files/en.lproj/Localizable.strings
- Tella/Supporting Files/es.lproj/Localizable.strings
- Tella/Supporting Files/fa-IR.lproj/Localizable.strings
- Tella/Supporting Files/fr.lproj/Localizable.strings
- Tella/Supporting Files/ku.lproj/Localizable.strings
- Tella/Supporting Files/my.lproj/Localizable.strings
- Tella/Supporting Files/ta.lproj/Localizable.strings
- Tella/Utils/Localizable/LocalizableVault.swift
CHange title when removing a folder
* If user remove a folder it should show "delete folder?" or "delete folders?" instead of showing the message of the file
* Change file message to also show the amount of files to be removed
*
> Change title when removing a folder

- Tella/Data/Networking/Models/UwaziCheckURLDTO.swift
- Tella/Data/Networking/Repositories/UwaziServerRepositories.swift
- Tella/Domain/Entity/Uwazi/UwaziCheckURL.swift
- Tella/Scenes/Settings/ViewModel/UwaziServerViewModel.swift
> handle 401 auth error when a private instance is trying to connect

- Tella/Scenes/Audio/Recorder/Views/RecordView.swift
- Tella/Scenes/Settings/Views/Common/SettingsItemView.swift
Show attempts selected on the "Delete after failed unlock" and a handle longer languages
> Handle longer languages in Settings

- Tella/Scenes/Authentication/Views/Lock/CommonView/BottomLockView.swift
- Tella/Scenes/Authentication/Views/Lock/CommonView/LockDescriptionView.swift
Add height for LockDescriptionView and adjust bottom padding for BottomLockView
> Add height for LockDescriptionView and adjust bottom padding for BottomLockView

- Tella/Data/Database/Common/DatabaseConstants.swift
- Tella/Data/Database/TellaDataBase.swift
- Tella/Data/Database/UwaziDatabase.swift
> add function to update uwaziTemplate in order to add relationship column

- Tella/Scenes/Uwazi/Utils/UwaziEntityParser.swift
- Tella/Scenes/Uwazi/ViewModel/UwaziEntityViewModel.swift
> fix relationship not showing up

- Tella/Components/TextfieldView.swift
- Tella/Scenes/Settings/Views/Servers/AddServer/ServerLoginView.swift
- Tella/Scenes/Settings/Views/Servers/Uwazi/Step3/UwaziLoginView.swift
- Tella/Scenes/Settings/Views/Servers/Uwazi/Step4/UwaziTwoStepVerification.swift
Hide password in Connections login views
> Hide password in Connections login views

- Tella.xcodeproj/project.pbxproj
- Tella/Scenes/Authentication/ViewModel/LockViewModel.swift
- Tella/Scenes/Authentication/Views/Lock/CommonView/BottomLockView.swift
- Tella/Scenes/Authentication/Views/Lock/LockChoice/LockChoiceView.swift
- Tella/Scenes/Authentication/Views/Lock/TransitionViews/WelcomeView.swift
- Tella/Scenes/Authentication/Views/Unlock/UnlockView.swift
- Tella/Scenes/Settings/Views/Security/SecuritySettingsView.swift
- Tella/Scenes/Settings/Views/Servers/AddServer/SuccessAdvancedSettingsView.swift
- Tella/Scenes/Settings/Views/Servers/Uwazi/Step6/UwaziSuccessView.swift
- Tella/Scenes/Uwazi/Views/Entity/CreateEntityView.swift
- Tella/Utils/ViewClassType.swift
Fix navigation issues on Lock  view
> Fix navigation issue on Lock  view

- Tella/Scenes/Uwazi/Utils/UwaziEntityParser.swift
- Tella/Scenes/Uwazi/Views/Entity/RenderPropertyComponentView.swift
- Tella/Scenes/Uwazi/Views/Entity/Widgets/UwaziSelectWidget.swift
* remove multiSelect property
* fix scrollView on single select
https://github.com/Horizontal-org/Tella-iOS/assets/9373006/2aea6e5c-c659-40f1-94d1-00738e7e845c
> remove multiselect and fix scrollview on single select

- Tella/Data/Networking/Repositories/ReportRepository.swift
> update new endpoint

- Tella/Scenes/Uwazi/Utils/UwaziEntityParser.swift
> 1.9.0-fixes

- Tella/Data/Database/TellaDataBase.swift
> fix migration issue

- .gitignore
- Tella.xcodeproj/project.pbxproj
> Add TellaConfig

- Tella/Data/Networking/APICall/APIError.swift
- Tella/Scenes/GDrive/ViewModel/GDriveOutboxViewModel.swift
- Tella/Scenes/Resources/ViewModel/ResourcesViewModel.swift
- Tella/Scenes/Settings/ViewModel/ServerViewModel.swift
- Tella/Scenes/Settings/ViewModel/UwaziServerViewModel.swift
- Tella/Scenes/Uwazi/ViewModel/AddTemplateVM.swift
- Tella/Utils/Utils.swift
> Refactor APIError errorMessage, remove optionnal message

- Tella/Scenes/Settings/ViewModel/ServersViewModel.swift
- Tella/Scenes/Settings/Views/Servers/ServerSelectionView.swift
> Select server view : Fix next button action

- Tella.xcodeproj/project.pbxproj
- Tella/Supporting Files/ar.lproj/Localizable.strings
- Tella/Supporting Files/be.lproj/Localizable.strings
- Tella/Supporting Files/en.lproj/Localizable.strings
- Tella/Supporting Files/es.lproj/Localizable.strings
- Tella/Supporting Files/fa-IR.lproj/Localizable.strings
- Tella/Supporting Files/fr.lproj/Localizable.strings
- Tella/Supporting Files/ku.lproj/Localizable.strings
- Tella/Supporting Files/my.lproj/Localizable.strings
- Tella/Supporting Files/pt-BR.lproj/Localizable.strings
- Tella/Supporting Files/ru.lproj/Localizable.strings
- Tella/Supporting Files/ta.lproj/Localizable.strings
- Tella/Supporting Files/vi.lproj/Localizable.strings
- Tella/Utils/Language/Language.swift
- Tella/Utils/Localizable/LocalizableSettings.swift
> add vietnamese localization

- Tella.xcodeproj/project.pbxproj
> tella config fixes

- Tella.xcodeproj/project.pbxproj
- Tella/Components/Modifiers/ScrollviewViewContentViewModifier.swift
- Tella/Scenes/CommonConnectionReport/ViewModels/DraftMainViewModel.swift
- Tella/Scenes/CommonConnectionReport/ViewModels/OutboxMainViewModel.swift
- Tella/Scenes/CommonConnectionReport/ViewModels/SubmittedMainViewModel.swift
- Tella/Scenes/CommonConnectionReport/Views/Draft/DraftView.swift
- Tella/Scenes/GDrive/ViewModel/GDriveDraftViewModel.swift
- Tella/Scenes/GDrive/ViewModel/GDriveOutboxViewModel.swift
- Tella/Scenes/GDrive/ViewModel/GDriveSubmittedViewModel.swift
- Tella/Scenes/GDrive/Views/Draft/GDriveDraftView.swift
- Tella/Scenes/GDrive/Views/GDriveSubmittedDetailsView.swift
- Tella/Scenes/GDrive/Views/GdriveOutboxDetailsView.swift
- Tella/Scenes/GDrive/Views/GdriveReportMainView.swift
- Tella/Scenes/Nextcloud/ViewModels/NextcloudDraftViewModel.swift
- Tella/Scenes/Nextcloud/ViewModels/NextcloudOutboxViewModel.swift
- Tella/Scenes/Nextcloud/ViewModels/NextcloudSubmittedViewModel.swift
- Tella/Scenes/Nextcloud/Views/NextcloudDraftView.swift
- Tella/Scenes/Nextcloud/Views/NextcloudReportMainView.swift
- Tella/Scenes/Nextcloud/Views/NextcloudSubmittedDetailsView.swift
- Tella/Scenes/Nextcloud/Views/NextcloutOutboxDetailsView.swift
- Tella/Scenes/Reports/Outbox/OutboxDetailsView.swift
- Tella/Scenes/Reports/Submitted/SubmittedDetailsView.swift
- Tella/Scenes/Reports/View Model/DraftReportVM.swift
- Tella/Scenes/Reports/View Model/OutboxReportVM.swift
- Tella/Scenes/Reports/View Model/SubmittedReportVM.swift
- Tella/Scenes/Reports/Views/TellaServerDraftView.swift
- Tella/Scenes/Reports/Views/TellaServerOutboxDetailsView.swift
- Tella/Scenes/Reports/Views/TellaServerReportsMainView.swift
- Tella/Scenes/Reports/Views/TellaServerSubmittedDetailsView.swift
- Tella/Scenes/Settings/Views/Servers/ServerSelectionView.swift
> Remove the redundant usage of reportsmainViewmodel and mainAppModel

- Tella/Scenes/Settings/ViewModel/DropboxServerViewModel.swift
- Tella/Scenes/Settings/Views/Servers/ServerSelectionView.swift
> Refactor Dropbox

- Tella/Scenes/Settings/Views/Servers/ServerSelectionView.swift
> Labels gets cut when there is an existing connection

- Tella/Scenes/Settings/Views/Servers/ServersListView.swift
> Fix edit connection title

- Tella/Components/Modifiers/ScrollviewViewContentViewModifier.swift
- Tella/Components/Tabs/PageView.swift
> Visual bug on entities card

- Tella/Scenes/Uwazi/Views/EntityInstances/UwaziListView.swift
>  visual bug on delete entity

- Tella/Components/ToastView.swift
> Update toast view to align with design

- Tella/Scenes/Settings/ViewModel/GDriveServerViewModel.swift
- Tella/Scenes/Settings/Views/Servers/GDrive/SelectDriveConnectionView.swift
- Tella/Utils/Constants.swift
* Hide shared drives button if user does not have any drives
* change documentation url
*
> disable shared drive button if is empty

- Tella/Components/BottomSheet/ConfirmBottomSheet.swift
- Tella/Components/ImportFilesProgressView/CancelImportView.swift
- Tella/Components/ImportFilesProgressView/ImportFilesProgressView.swift
- Tella/Data/VaultManager/FilesActor.swift
- Tella/Data/VaultManager/ImportProgress.swift
- Tella/Data/VaultManager/VaultFilesManager.swift
- Tella/Data/VaultManager/VaultFilesManagerExtension.swift
- Tella/Scenes/CommonConnectionReport/Views/Draft/AddFilesToDraftView.swift
- Tella/Scenes/HomeView/Views/FileListView/Add files/PhotoVideoPickerView.swift
- Tella/Scenes/HomeView/Views/FileListView/Add files/PhotoVideoViewModel.swift
- Tella/Utils/Extensions/PHAssetExtension.swift
- Tella/Utils/Extensions/URLExtension.swift
> T-iOS-488 - Fix Importing files in reports bugs

- Tella/Domain/Entity/Report/Vault/VaultFileDB.swift
- Tella/Scenes/Audio/AudioPlayer/AudioPlayerManager/AudioPlayer.swift
- Tella/Scenes/Audio/AudioPlayer/AudioPlayerManager/AudioPlayerManager.swift
- Tella/Scenes/Audio/AudioPlayer/ViewModel/AudioPlayerViewModel.swift
- Tella/Scenes/Audio/AudioPlayer/ViewModel/EditAudioViewModel.swift
- Tella/Scenes/Audio/AudioPlayer/Views/EditAudioView.swift
- Tella/Scenes/HomeView/Views/FileDetailView/FileDetailsView.swift
- Tella/Scenes/HomeView/Views/FileListView/File list/MoreFileActionButton.swift
> Fix EditAudio Display issue

- Tella/Supporting Files/en.lproj/Localizable.strings
> T-iOS-539 - Change text in Quick Delete to say "Delete files"

- Tella/Scenes/Authentication/Views/Lock/CommonView/LockDescriptionView.swift
> T-iOS-541 - Label gets cut off for password setup

- Tella/Scenes/Uwazi/Views/Entity/SummaryEntityView.swift
> T-iOS-517 - submit sceen not scrollable (button inaccessible)

- Tella/Supporting Files/en.lproj/Localizable.strings
> T-iOS-534 - Change the text of the edit media confirmation message

- Tella/Scenes/HomeView/Views/FileListView/File list/FileItemsView.swift
> T-iOS-525 -  Interface bug in all files folder 

- Tella/Scenes/HomeView/Views/Home/HomeView.swift
- Tella/Scenes/HomeView/Views/Home/QuickDelete/QuickDeleteView.swift
> T-iOS-393 - Make all elements in homescreen scrollable, do not keep connections and recent files fixed on the top

- Tella/Scenes/Settings/Views/Security/SecuritySettingsView.swift
- Tella/Scenes/Settings/Views/SettingsMainView.swift
- Tella/Utils/ViewClassType.swift
> T-iOS-544 - Unable to go back after updating the password/pin in Settings

- Tella/Scenes/Camera/Views/CameraControlsView.swift
- Tella/Scenes/HomeView/Views/FileDetailView/FileDetailsView.swift
- Tella/Scenes/HomeView/Views/FileDetailView/Video/VideoViewer.swift
- Tella/Scenes/HomeView/Views/FileListView/File list/FileListView.swift
- Tella/Scenes/HomeView/Views/Home/Recent files/RecentFilesListView.swift
- Tella/Utils/Extensions/UIApplicationExtension.swift
- Tella/Utils/Extensions/ViewExtension.swift
- Tella/Utils/ViewClassType.swift
> T-iOS-524 - navigation problem in all files folder (only with videos) 
